Controllers/AdminLayoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyAkademiRapidApi.Controllers
{
	public class AdminLayoutController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;
using MyAkademiRapidApi.Models;
using Newtonsoft.Json;

namespace MyAkademiRapidApi.Controllers
{
    public class BookingController : Controller
    {
        public async Task<IActionResult> Index(IFormCollection data)
        {
            var city = data["CityCode"].ToString();
            var checkInDate = data["CheckIn"].ToString();
            var checkOutDate = data["CheckOut"].ToString();
            var children = data["ChildrenCount"].ToString();
            if(city != null && checkInDate != null && checkOutDate != null && children != null)
            {
                var clientSearhID = new HttpClient();
                var requestSearhID = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://booking-com.p.rapidapi.com/v1/hotels/locations?name={city}"+ "&locale=en-gb"),
                    Headers =
                    {
                        { "X-RapidAPI-Key", "941cfb51ebmsh9c789303add2982p1062c5jsn08a9b508ce41" },
                        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
                    },
                };
                    var responseID = await clientSearhID.SendAsync(requestSearhID);
                
                    responseID.EnsureSuccessStatusCode();
                    var bodyID = await responseID.Content.ReadAsStringAsync();
                    var valuesID = JsonConvert.DeserializeObject<List<SearchLocationViewModel>>(bodyID);
                    var CityID= valuesID.Select(x=>x.dest_id).FirstOrDefault();
                    
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://booking-com.p.rapidapi.com/v1/hotels/search?order_by=popularity&checkout_date={checkOutDate}&filter_by_currency=AED&locale=en-gb&units=metric&dest_id={CityID}&dest_type=city&adults_number=2&room_number=1&checkin_date={checkInDate}&include_adjacency=true&page_number=0&children_number={children}&categories_filter_ids=class%3A%3A2%2Cclass%3A%3A4%2Cfree_cancellation%3A%3A1&children_ages=5%2C0"),
                    Headers =
                    {
                        { "X-RapidAPI-Key", "941cfb51ebmsh9c789303add2982p1062c5jsn08a9b508ce41" },
                        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
                    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var values = JsonConvert.DeserializeObject<BookingViewModel>(body);
                    return View(values.result.ToList());
                }
                
            }
            else
            {
            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://booking-com.p.rapidapi.com/v1/hotels/search?order_by=popularity&checkout_date=2024-05-20&filter_by_currency=AED&locale=en-gb&units=metric&dest_id=-1456928&dest_type=city&adults_number=2&room_number=1&checkin_date=2024-05-19&include_adjacency=true&page_number=0&children_number=2&categories_filter_ids=class%3A%3A2%2Cclass%3A%3A4%2Cfree_cancellation%3A%3A1&children_ages=5%2C0"),
                Headers =
    {
        { "X-RapidAPI-Key", "941cfb51ebmsh9c789303add2982p1062c5jsn08a9b508ce41" },
        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
    },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<BookingViewModel>(body);
                return View(values.result.ToList());
            }
            return View();
            }
            
        }
    }
}

Controllers/ExchangeController.cs
using Microsoft.AspNetCore.Mvc;
using MyAkademiRapidApi.Models;
using Newtonsoft.Json;

namespace MyAkademiRapidApi.Controllers
{
    public class ExchangeController : Controller
    {
        public async Task<IActionResult> Index(IFormCollection data)
        {
            var moneyType = data["txtValue1"].ToString();
            if (moneyType != null)
            {



                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://booking-com.p.rapidapi.com/v1/metadata/exchange-rates?currency={moneyType}&locale=en-gb"),
                    Headers =
    {
        { "X-RapidAPI-Key", "941cfb51ebmsh9c789303add2982p1062c5jsn08a9b508ce41" },
        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var values = JsonConvert.DeserializeObject<ExchangeViewModel>(body);
                    return View(values.exchange_rates.ToList());
                }
            }
            else
            {

            
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                 Method = HttpMethod.Get,
                 RequestUri = new Uri("https://booking-com.p.rapidapi.com/v1/metadata/exchange-rates?currency=USD&locale=en-gb"),
                  Headers =
        {
            { "X-RapidAPI-Key", "941cfb51ebmsh9c789303add2982p1062c5jsn08a9b508ce41" },
            { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
        },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var values = JsonConvert.DeserializeObject<ExchangeViewModel>(body);
                    return View(values.exchange_rates.ToList());
                }
            }
        }
    }
}

Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using MyAkademiRapidApi.Models;
using Newtonsoft.Json;

namespace MyAkademiRapidApi.Controllers
{
	public class WeatherController : Controller
	{
		public async Task<IActionResult> Index(IFormCollection data)
		{
			var city = data["city"].ToString();
			
			var client = new HttpClient();
			var request = new HttpRequestMessage
			{
				Method = HttpMethod.Get,
				RequestUri = new Uri($"https://yahoo-weather5.p.rapidapi.com/weather?location={city}&format=json&u=c"),
				Headers =
	{
		{ "X-RapidAPI-Key", "941cfb51ebmsh9c789303add2982p1062c5jsn08a9b508ce41" },
		{ "X-RapidAPI-Host", "yahoo-weather5.p.rapidapi.com" },
	},
			};
			using (var response = await client.SendAsync(request))
			{
				response.EnsureSuccessStatusCode();
				var body = await response.Content.ReadAsStringAsync();
				var values = JsonConvert.DeserializeObject<WeatherViewModel>(body);
				return View(values);
			}
		}
	}
}

Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/material-lite-master/assets/images/favicon.png">
    <title>Rapid Api Projeleri</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/material-lite-master/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/material-lite-master/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="~/material-lite-master/css/colors/blue.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-toggleable-sm navbar-light">
                
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                   
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav my-lg-0">
                        <!-- ============================================================== -->
                        <!-- Profile -->
                        <!-- ============================================================== -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark">Oğuzhan KARAL</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar" style="width:350px">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li>
                            <a class="waves-effect waves-dark" href="/MoviesSeries/Index" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">IMDB</span></a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="/Weather/Index" aria-expanded="false"><i class="mdi mdi-account-check"></i><span class="hide-menu">Hava Durumu</span></a>
                            <form method="post" asp-action="Index" asp-controller="Weather">
                                <input type="text" name="City" placeholder="Şehir Giriniz.." />
                                <button class="btn btn-outline-warning">Gönder</button>
                            </form>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="/Exchange/Index" aria-expanded="false"><i class="mdi mdi-table"></i><span class="hide-menu">Kur Hesaplayıcı</span></a>
                            <form method="post" asp-action="Index" asp-controller="Exchange">
                                <input type="text" name="txtValue1" />
                                <button class="btn btn-outline-success">Gönder</button>
                            </form>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="/SearchLocation/Index" aria-expanded="false"><i class="mdi mdi-emoticon"></i><span class="hide-menu">Koordinat Öğren</span></a>
                        </li>
                        <li>        
                                <a class="waves-effect waves-dark" href="/Booking/Index" aria-expanded="false"><i class="mdi mdi-earth"></i><span class="hide-menu">Booking App</span></a>
                                    <form method="post" asp-action="Index" asp-controller="Booking" >
                                        <input type="text" name="CityCode" placeholder="Gitmek İstediğiniz Şehri Yazınız" style="width:330px" /><br /><br />
                                        <input type="text" name="CheckIn" placeholder="Lütfen Giriş Tarihinizi Yazınız Örn:YYYY-AA-GG" style="width:330px" /><br /><br />
                                        <input type="text" name="CheckOut" placeholder="Lütfen Çıkış Tarihinizi Yazınız Örn:YYYY-AA-GG" style="width:330px" /><br /><br />
                                        <input type="text" name="ChildrenCount" placeholder="Lütfen Çocuk Sayınızı Yazınız" style="width:330px" /><br /><br />
                                        <button class="btn btn-outline-primary">Otelleri Sırala</button>
								    </form>					
                        </li>
                    </ul>
                    
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
            <!-- Bottom points-->
            <div class="sidebar-footer">
                <!-- item--><a href="" class="link" data-toggle="tooltip" title="Settings"><i class="ti-settings"></i></a>
                <!-- item--><a href="" class="link" data-toggle="tooltip" title="Email"><i class="mdi mdi-gmail"></i></a>
                <!-- item--><a href="" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>
            </div>
            <!-- End Bottom points-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <br /><br />
                @RenderBody()
               
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <footer class="footer">
                © 2017 Material Pro Admin by wrappixel.com
            </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="~/material-lite-master/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/material-lite-master/assets/plugins/bootstrap/js/tether.min.js"></script>
    <script src="~/material-lite-master/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="~/material-lite-master/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="~/material-lite-master/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="~/material-lite-master/js/sidebarmenu.js"></script>
    <!--stickey kit -->
    <script src="~/material-lite-master/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <!--Custom JavaScript -->
    <script src="~/material-lite-master/js/custom.min.js"></script>
</body>

</html>